apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:
      - superuser
      - createdb
    airflow_user:
      - superuser
      - createdb
  databases:
    foo: zalando
    airflow_db: airflow_user
  preparedDatabases:
    bar: {}
  postgresql:
    version: "13"