# This file is a template, and might need editing before it works on your project.
# Official image for Hashicorp's Terraform. It uses light image which is Alpine
# based as it is much lighter.
#
# Entrypoint is also needed as image by default set `terraform` binary as an
# entrypoint.
image:
  name: hashicorp/terraform:0.14.7
  entrypoint: [""]
#  entrypoint:
#    - '/usr/bin/env'
#    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json
  DOCKER_VERSION: 19.03.12
  IMAGE_NAME: tbd-os

cache:
  paths:
    - .terraform
    - .terraform.lock.hcl

before_script:
  - terraform --version
  - terraform init

stages:
  - validate
  - buildPublish

validate:
  stage: validate
  script:
    - terraform validate
  tags: [ docker ]


.buildPublish: &buildPublish
  image:
    name: docker:$DOCKER_VERSION
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD docker.io
  script:
    - cd docker/
    - docker build
      -t $IMAGE_NAME
      .
    - docker push $IMAGE_NAME
  tags: [ docker ]
  
  buildPublishDefault:
  stage: buildPublish
  variables:
    <<: *defaultImageVars
  <<: *buildPublish
  except: [ master ]