prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchExpressions:
        - key: app
          operator: In
          values:
            - prometheus-pushgateway
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    retention: 180d

grafana:
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi