{
 "title": "Kubernetes - Apache Spark Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application_name",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_executor_completedTasks_total, application_name)"
    }
   },
   {
    "name": "application_id",
    "label": "Application ID",
    "query": {
     "query": "label_values(metrics_executor_activeTasks, application_id)"
    }
   },
   {
    "name": "run_id",
    "label": "Application run",
    "query": {
     "query": "label_values(executorcputime,run_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executor runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(executorruntime{run_id=~\"$run_id\"}) by (job,run_id)",
     "legendFormat": "{{job}}-{{run_id}}"
    }
   ]
  },
  {
   "title": "Executor CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(executorcputime{run_id=~\"$run_id\"}) by (job,run_id)",
     "legendFormat": "{{job}}-{{run_id}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(jvmgctime{run_id=~\"$run_id\"}) by (job,run_id)",
     "legendFormat": "{{job}}-{{run_id}}"
    }
   ]
  },
  {
   "title": "Shuffle wait time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(shufflefetchwaittime{run_id=~\"$run_id\"}) by (job,run_id)",
     "legendFormat": "{{job}}-{{run_id}}"
    }
   ]
  },
  { "title": "Spark Executor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "JVM Heap per executor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_JVMHeapMemory_bytes{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_name,application_id,executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalCores{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_nam,application_id)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Total tasks completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_name,application_id)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "  sum(metrics_executor_JVMHeapMemory_bytes{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_name,application_id,executor_id)",
     "legendFormat": "{{application_name}}-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Total task duration on executors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(metrics_executor_totalDuration_seconds_total{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_name,application_id)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Total shuffle read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "  sum(metrics_executor_totalShuffleRead_bytes_total{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_name,application_id)",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Total GC Time ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_totalGCTime_seconds_total{application_id=~\"$application_id\", application_name=\"$application_name\"}) by (application_name,application_id)\n",
     "legendFormat": "{{application_name}}"
    }
   ]
  }
 ]
}