{
 "title": "Apache Spark - Performance Metrics ",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "driver",
    "label": "Driver ID",
    "query": "label_values(kube_pod_info, pod)"
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": "label_values(kube_pod_info{created_by_name=~\"$driver\"},pod)"
   },
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": "label_values(kube_pod_info{pod=\"$driver\"}, pod_ip)"
   },
   {
    "name": "phase",
    "query": "query_result(kube_pod_status_phase{pod=\"$driver\"})"
   },
   { "name": "copy_of_phase" }
  ]
 },
 "panels": [
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "repeat": "Driver",
   "content": "# $pod_ip"
  },
  {
   "title": "Driver Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "repeat": "Pod",
   "content": "# $phase"
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Driver Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"^$driver$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\"})  * 100"
      }
     ]
    },
    {
     "title": "Executor Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod=~\"^$executor$\"}) / sum (machine_memory_bytes{node=~\"^$node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"^$driver$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"^$executor$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver CPU / Memory  usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "repeat": "Pod",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{ pod!=\"\", pod=\"$driver\"}) by (pod)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Driver CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none", "label": "CPU Time" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$driver$\"} [2m])) by (pod) ",
       "legendFormat": "Used CPU : {{pod_name}}"
      }
     ]
    },
    {
     "title": "Driver GC : Seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{name=~\"$Pod\",gc=\"PS Scavenge\"}",
       "legendFormat": "{{ gc }}"
      },
      {
       "expr": "jvm_gc_collection_seconds_count{name=~\"$Pod\",gc=\"PS MarkSweep\"}",
       "legendFormat": "{{ gc }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor CPU /Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor :  Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{ pod!=\"\",pod=~\"$executor\"}) by (pod)",
       "legendFormat": "{{pod_name}} "
      }
     ]
    },
    {
     "title": "Executor  :  CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "CPU Time" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$executor\"} [4m])) by (pod) ",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Executor GC : Seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$executor\",gc=\"PS Scavenge\"}",
       "legendFormat": "{{ kubernetes_pod_name }} {{ gc }}"
      },
      {
       "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$executor\",gc=\"PS MarkSweep\"}",
       "legendFormat": "{{ kubernetes_pod_name }} {{ gc }}"
      }
     ]
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Driver Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$driver'}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$driver'}[2m])) by (pod)",
     "legendFormat": "{{ pod }}  Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$executor', node=~\"$node\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }} {{ node }} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$executor',pod!=\"pod\",node=~\"$node\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }} {{ node }}  Received"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$driver|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }} {{ device }} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$driver|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }}{{device}} Write"
    }
   ]
  },
  { "title": "Spark External Shuffle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Spark Shuffle Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'.*shuffle.*',node=~\"$node\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod  }} {{ node }} Transmitted"
    }
   ]
  },
  {
   "title": "Spark Shuffle Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~'.*shuffle.*',pod!=\"pod\",node=~\"$node\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }} {{ node }}  Received"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }} {{ device }} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$driver|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod,device)",
     "legendFormat": "{{ pod }}{{ device }} Write"
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"^$Pod$\",area=\"heap\"} ",
       "legendFormat": "{{ name }} "
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"^$executor$\",area=\"heap\"}",
       "legendFormat": " {{ kubernetes_pod_name }} "
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"$Pod\",area=\"nonheap\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"$executor\",area=\"nonheap\"}",
       "legendFormat": "{{kubernetes_pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads & Memory Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name,pool)",
       "legendFormat": "{{ kubernetes_pod_name }} {{pool}}"
      },
      {
       "expr": "sum(jvm_memory_pool_bytes_used{name=~\"$Pod\"}) by (name,pool)",
       "legendFormat": "{{ name }} {{pool}}"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_current{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {
       "expr": "sum(jvm_threads_current{name=~\"$Pod\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Executor : Completed Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_completetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    },
    {
     "title": "Executor : Active Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_activetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors Spawned",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_name=~\"$driver\"})",
       "legendFormat": "Executor Counts "
      }
     ]
    },
    {
     "title": "Packets Dropped : Network",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total{pod=~\"$driver|$executor\"}",
       "legendFormat": "{{ pod }} - Receive"
      },
      {
       "expr": "container_network_transmit_packets_dropped_total{pod=~\"$driver|$executor\"}",
       "legendFormat": "{{ pod }} - Transmit"
      }
     ]
    },
    {
     "title": "Kubernetes Pod Slice",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 29 },
     "targets": [
      {
       "expr": "container_network_receive_bytes_total{pod=~\"$executor\"}"
      },
      {
       "expr": "container_network_receive_bytes_total{pod=~\"$driver\"}"
      },
      {}
     ]
    }
   ]
  }
 ]
}