apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: spark
    spark-role: driver
    release: prometheus-community
  name: spark-servicemonitor
spec:
  endpoints:
    - interval: 5s
      port: spark-ui
      path: /metrics/executors/prometheus/
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      sparkSvc: driver